name: Tests

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Lint allowed branch names
        uses: lekterable/branchlint-action@1.2.0
        with:
          allowed: |
            /^(.+:)?bugfix/.+/i
            /^(.+:)?docs?/.+/i
            /^(.+:)?feature/.+/i
            /^(.+:)?hotfix/.+/i
            /^(.+:)?major/.+/i
            /^(.+:)?misc/.+/i
            /^(.+:)?develop$/i
      -
        name: Block fixup/squash commits
        uses: xt0rted/block-autosquash-commits-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      -
        # Run only for release branch
        if: ${{ github.base_ref == 'release' }}
        name: Check for changelog pattern
        uses: gandarez/check-pr-body-action@v1.0.3
        with:
          pr_number: ${{ github.event.number }}
          contains: 'Changelog:'
          not_contains: '`'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
